name: OpenHands Code Quality Review (Direct Push - UNSAFE EXAMPLE)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-quality-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # CRITICAL:  Allows writing to the repo!
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }} # Check out the specific PR commit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openhands-ai black mypy ruff

      - name: Run OpenHands Review (and potentially modify code)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: "claude-3-5-sonnet-20241022"
          LOG_ALL_EVENTS: "true"
        run: |
          # Verify .openhands_instructions exists
          if [ ! -f ".openhands_instructions" ]; then
            echo "Error: .openhands_instructions file not found in repository"
            exit 1
          fi

          # Run OpenHands review - NO GOOD/BAD requirement
          review_output=$(python -m openhands.core.main \
            -t "Review PR #${{ github.event.pull_request.number }} in ${{ github.repository }} according to .openhands_instructions. Identify and fix code quality issues directly." \
            --eval-output-dir ./eval_output \
            --no-auto-continue \
            -i 50 \
            -b 50 \
            --eval-n-limit 50)

          echo "$review_output" > openhands_output.txt  # Save for debugging

          # ---  GIT OPERATIONS  ---
          git config --global user.name "OpenHands Bot"
          git config --global user.email "openhands-bot@example.com" # Replace with a real email

          # Check if there were changes
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Automated code quality improvements by OpenHands"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}  # Push to the PR branch
            echo "Changes pushed to the pull request."
          else
            echo "No changes made by OpenHands."
          fi

      - name: Comment on PR with OpenHands Output
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "OpenHands review output:
          \`\`\`
          $(cat openhands_output.txt || echo "No output available")
          \`\`\`"
