- name: Process review results
  env:
    GH_TOKEN: ${{ github.token }}
  run: |
    # Read the quality report
    QUALITY_REPORT=$(cat quality_report.md)
    
    if [ "$BLACK_PASSED" = "true" ] && [ "$RUFF_PASSED" = "true" ] && [ "$MYPY_PASSED" = "true" ]; then
      # If all automated checks passed, check OpenHands review output
      if grep -q "GOOD" ./eval_output/*; then
        # All checks passed and OpenHands approved - approve and auto-merge
        gh pr comment "${{ github.event.pull_request.number }}" --body "✅ **Code Quality Review Passed**

        All automated checks and OpenHands review passed. Auto-merging PR.

        $QUALITY_REPORT"
        
        gh pr review "${{ github.event.pull_request.number }}" --approve -b "All code quality standards met."
        
        # Enable auto-merge
        gh pr merge "${{ github.event.pull_request.number }}" --auto --merge
        gh pr merge "${{ github.event.pull_request.number }}" --merge
      else
        # OpenHands rejected
        gh pr comment "${{ github.event.pull_request.number }}" --body "❌ **Code Quality Review Failed**

        While automated checks passed, OpenHands AI review found quality issues. Please review your code for potential improvements.

        $QUALITY_REPORT"
        
        gh pr review "${{ github.event.pull_request.number }}" --request-changes -b "Code quality standards not met. See the detailed report in the PR comments."
      fi
    else
      # Some automated checks failed
      gh pr comment "${{ github.event.pull_request.number }}" --body "❌ **Code Quality Review Failed**

      Some quality checks did not pass. Please review the report below and make necessary changes.

      $QUALITY_REPORT"
      
      gh pr review "${{ github.event.pull_request.number }}" --request-changes -b "Code quality standards not met. See the detailed report in the PR comments."
    fi
